		<footer class="footer">
	      <div class="container">
					<a href="https://www.positivessl.com" style="font-family: arial; font-size: 10px; color: #212121; text-decoration: none;"><img src="https://www.positivessl.com/images-new/PositiveSSL_tl_trans.png" alt="SSL Certificate" title="SSL Certificate" border="0" /></a>
					<h4>Bill Account Manager</h4>
					<div style="font-family: arial;font-weight:bold;font-size:15px;color:#86BEE0;"><a href="mailto:info@billaccountmanager.com?subject=Info""><i class="fa fa-envelope-o" aria-hidden="true"></i> info@billaccountmanager.com</a></div>
	        <p class="copy">&copy; <?php echo date("Y") ?> billaccountmanager.com. All Rights Reserved.</p>
	      </div>
    	</footer>
    </body>

</html>
