<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Bill Account Manager</title>

        <!-- Bootstrap Core CSS -->
        <link href="assets/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="assets/css/custom-styles.css?version=1.5" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="assets/css/bootstrap-overrides.css?version=1.3" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="assets/css/mbile-friendly-api.css" rel="stylesheet">


         <!-- Font Awesome CSS -->
        <link href="assets/css/font-awesome.min.css" rel="stylesheet">

         <!-- Font Awesome CSS -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/bs/dt-1.10.11,cr-1.3.1,r-2.0.2,rr-1.1.1/datatables.min.css"/>

        <!-- dataTables overrides -->
         <link rel="stylesheet" href="assets/css/dataTables-overrides.css">

         <!-- dataTables overrides -->
        <link rel="stylesheet" href="assets/css/buttons.dataTables.min.css">

         <!-- datetime picker -->
         <link rel="stylesheet" href="assets/css/jquery-ui.min.css">

         <!-- slider css -->
         <link rel="stylesheet" href="assets/css/slider.css">

        <!-- full calalendar -->
         <link rel='stylesheet' href='node_modules/fullcalendar/dist/fullcalendar.css' />

        <!-- sweetalerts -->
        <script src="node_modules/sweetalert2/dist/sweetalert2.min.js"></script>
        <link rel="stylesheet" href="node_modules/sweetalert2/dist/sweetalert2.min.css">

        <!-- favicon -->
        <link rel="icon" href="img/favicon.ico" type="image/x-icon" />

        <!-- jQuery -->
        <script src="assets/js/jquery.js"></script>

        <!-- Date time picker -->
        <script src="assets/js/jquery-ui.min.js"></script>

        <!-- moment for full calendar -->
        <script src='node_modules/moment/moment.js'></script>

        <!-- full calendar -->
        <script src='node_modules/fullcalendar/dist/fullcalendar.js'></script>



        <!-- DataTables Core JavaScript -->
       <script type="text/javascript" src="https://cdn.datatables.net/t/bs/dt-1.10.11,cr-1.3.1,r-2.0.2,rr-1.1.1/datatables.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="assets/js/bootstrap.min.js"></script>

        <!-- Scrolling Nav JavaScript -->
        <script src="assets/js/jquery.easing.min.js"></script>

        <!-- js masking -->
        <script src="assets/js/jquery.maskedinput.min.js"></script>

        <!-- slider JavaScript -->
        <script src="assets/js/bootstrap-slider.js"></script>

        <!-- masonry -->
        <script src="assets/js/masonry.pkgd.min.js"></script>

        <!-- sweetalerts -->
        <script src="node_modules/sweetalert2/dist/sweetalert2.all.min.js"></script>
        <!-- Include a polyfill for ES6 Promises (optional) for IE11 and Android browser -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>

        <!-- custom js -->
        <script src="assets/js/custom.js"></script>

        <!-- table dataTable settings -->
        <script src="assets/js/table-dataTable-settings.js"></script>

        <!-- functions js -->
        <script src="assets/js/functions.js"></script>


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->


    </head>

    <!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

    <body>

        <!-- main navigation -->
        <?php include("includes/layouts/main_nav.inc") ?>
