<section class="c-section-content-1" id="bam-snippets">
	<div class="container">
		<div class="row clearfix bam-snippet-row">
			<!-- overview -->
			<div class="col-md-6 text-center">
				<img class="img-responsive center-block" src="img/overview.png" alt="BAM Overview Snippet">
			</div>
			<div class="col-md-6">
				<h3><strong>A simple breakdown of your bills.</strong></h3>
				<p>No need to search through your paper bills, or log into every single site to see what is due and when. Simply add your bills to your BAM account and you will get a complete breakdown on what is due next, what is late and more.</p>
			</div>
		</div>
			
		<div class="row clearfix bam-snippet-row">
			<div class="col-md-6 text-center">
				<img class="img-responsive center-block" src="img/bills.png" alt="BAM Overview Snippet">
			</div>
			<div class="col-md-6">
				<h3><strong>Beautiful, clean responsive tables.</strong></h3>
				<p>Each and every table is responsive. Utilizing the <a href="https://datatables.net/" target="_blank">DataTables</a> framework and its responsive extension you can view your Bam account on any device comfortably. <strong>No need to scroll side to side on a mobile device.</strong></p>
			</div>
		</div>	
			
	</div>
</section>