<section class="c-section-content-1" id="features-section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="text-center features-title">Your personal bill account manager.</h1>
				<p class="lead text-center features-about">BAM helps you stay a little more organized when it comes to keeping track of your current bills and accounts. With an easy to read dashboard you can view your total bills due, past due bills and much more.</p>
			<hr>
			</div>

			<!-- history -->
			<div class="col-sm-4 text-center">
				<img class="img-responsive history" src="img/bill_history.png" alt="Bill History">
				<h3>History</h3>
				<p>View your payment history at any given time, for any particular bill or account. Dates, confirmation numbers available when you need them.</p>
			</div>

			<!-- dashboard -->
			<div class="col-sm-4 text-center">
				<img class="img-responsive history" src="img/dashboard.png" alt="User Dashboard">
				<h3>User Dashboard</h3>
				<p>A simple easy to follow breakdown of your accounts and bills. Active bills, late bills, on time vs. late payments ratio. </p>
			</div>

			<!-- free -->
			<div class="col-sm-4 text-center">
				<img class="img-responsive history" src="img/free_to_use.png" alt="Free To Use">
				<h3>Free</h3>
				<p>100% Free to use. Register today, login and start calculating your current bills. Currently in BETA, new features will be added frequently.</p>
			</div>
		</div>
	</div>
</section>