<section class="c-section-content-1" id="hero-section">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-4 col-sm-offset-4 c-white text-center">
				<img class="hero-logo-img center-block" src="img/BAM-logo.png" alt="BAM HERO IMAGE">
				<p class="lead hero-welcome c-text-shadow-1">BAM is a Bill Account Manager that helps you organize your current accounts and bills all in one place.</p>
				<!-- <a class="btn c-btn-1 btn-lg" href="register.php">Register For Free Today</a> -->
				<p class="version">Currently in BETA</p>
			</div>
		</div>
	</div>
</section>